### ISSUE TITLE
how to use the program

### ISSUE THREAD

**Issue by onionysy** [adderbyte/GYM_XPLANE_ML#3]
could you please tell me the detail about how to use the program?
thank you very much!

**Comment by adderbyte** [comment]
Hi,
Assuming you are familiar with the Gym environment (https://gym.openai.com/envs/#classic_control)  then the program should be easy to use.
You need only to follow the installation steps in the Read me below:
https://github.com/adderbyte/GYM_XPLANE_ML/tree/master/gym_xplane_final_version

This is essentially the gym xplane final version that could be installed easily.

You need to have Xplane installed. After this you define the flight scenario  in  xplane or use the scenario provided in the  repository as a test (check the  files in the second link). 
Gym Xplane would interact with the Xplane simulation by sending commands that will navigate the aircraft.

I hope this helps !
Let me know if there is any other thing that I should explain or elaborate.

**Comment by DragonSongjg** [comment]
Is the version of x-plane specific？ The Demo or the Completed Version？ v11.0 or v10.0？

**Comment by adderbyte** [comment]
Hi,
There is the final version https://github.com/adderbyte/GYM_XPLANE_ML/tree/master/gym_xplane_final_version which is straight forward to run.
 The other version https://github.com/adderbyte/GYM_XPLANE_ML/tree/master/gym_xplane_envirnment 
contains some functionality that is being tested.  

Both versions can be used but the final version is easier to set up.

Best regards.

**Comment by goudon123** [comment]
![image](https://user-images.githubusercontent.com/34227762/107328716-7f947e00-6af2-11eb-8a68-51265fde5849.png)
![image](https://user-images.githubusercontent.com/34227762/107328755-8de29a00-6af2-11eb-9db2-2506026c2c0d.png)

Hi I followed the steps and instructions on how to install gym_xplane and XPC, and now I trying to run the random_agent.py fromhttps://github.com/adderbyte/GYM_XPLANE_ML/tree/master/gym_xplane_final_version/examples

But the code does not interact with the X-plane simulator, and keep showing the **[0 0 0 0 0 0 0 0 0 0 0] False action** as shown in the pictures above. May I know what problem is this?
