### ISSUE TITLE
Can't import gym_xplane

### ISSUE THREAD

**Issue by aerosn** [adderbyte/GYM_XPLANE_ML#5]
Hi,
I can't seem to run random_agents.py because the console said ModuleNotFoundError: No module named 'gym_xplane'

I've followed the instruction, and that's something i got. Can anyone help? Is there any other way to install the gym_xplane package without easy install? I'm using Windows 10 btw.

Another thing I want to ask is I try to pip install in gym_xplane directory but it doesn't have setup.py so i moved the setup.py in the upper directory here. Is it wrong? Thank you.

**Comment by aerosn** [comment]
I've managed to solve it by tweaking the python a bit.

**Comment by lasri049** [comment]
> I've managed to solve it by tweaking the python a bit.

Can you please elaborate on this?

Thanks
Lakshmi
